### PR TITLE
PHPStorm series added

### PR DESCRIPTION
**Pull request by TomasVotruba**
This is a great series about PHPStorm, you can learn lot from.
I recommend it to everyone using IDE.

### CODE REVIEW

**Comment by shameerc** [comment]
Thanks @TomasVotruba! This is awesome!

**Comment by TomasVotruba** [comment]
:+1:

**Comment by TomasVotruba** [comment]
Btw, do you have any hint, what kind of videos are you interested in? Maybe some `CONTRIBUTING.md` file?

I know plenty, maybe even some meta-sources, like Laracasts I mentioned, so some rules might prevent flooding with spam.

**Comment by shameerc** [comment]
Yeah, I want keep the list as short as possible and have only the best talks. 
I've just added [contributing guidelines](CONTRIBUTING.md).  Tutorial videos are ruled out, though I'm keeping PHPStorm link :)

**Comment by TomasVotruba** [comment]
That's exactly what I had in mind. Thanks :)

**Pull request merged**
